SELECT *,
CASE WHEN 5 < MONTH(METTOL) AND MONTH(METTOL) < 9 THEN 'IGEN' ELSE 'NEM' END AS 'IGEN/NEM'
FROM FOGLALAS
WHERE UGYFEL_FK LIKE 'laszlo2' AND GYERMEK_SZAM LIKE '0'

--feladat2
SELECT szh.TIPUS, YEAR(f.METTOL) AS 'Év', MONTH(f.METTOL) AS 'Hónap', COUNT(*)
FROM Foglalas f JOIN Szoba sz ON f.SZOBA_FK = sz.SZOBA_ID 
JOIN Szallashely szh ON sz.SZALLAS_FK = szh.SZALLAS_ID
WHERE DATEDIFF(day, f.METTOL, f.MEDDIG)>=5 
GROUP BY szh.TIPUS, YEAR(f.METTOL), MONTH(f.METTOL)